const $=s=>document.querySelector(s);
const loader=$('#loader'), music=$('#weddingMusic'), cover=$('#cover'), site=$('#site');
let progress=0;
function finishLoader(){
  const step=()=>{progress=Math.min(100,progress+8);$('#loaderPercent').textContent=progress+'%';if(progress<100)setTimeout(step,38);else setTimeout(()=>{loader.classList.add('hide');},260)};step();
}
if(document.readyState==='complete') finishLoader(); else window.addEventListener('load',finishLoader,{once:true});
const params=new URLSearchParams(location.search);const guest=(params.get('n')||params.get('to')||'You').trim();$('#recipient').textContent=guest;
$('#openInvitation').addEventListener('click',()=>{document.body.classList.remove('locked');cover.style.display='none';site.classList.add('show');site.setAttribute('aria-hidden','false');window.scrollTo(0,0);music.play().catch(()=>{});});
$('#musicBtn').addEventListener('click',()=>{if(music.paused){music.play().catch(()=>{});$('#musicBtn').textContent='♫';}else{music.pause();$('#musicBtn').textContent='♪';}});
const target=new Date('2026-10-16T10:00:00+08:00').getTime();
function tick(){let d=Math.max(0,target-Date.now());const day=Math.floor(d/864e5);d%=864e5;const h=Math.floor(d/36e5);d%=36e5;const m=Math.floor(d/6e4);d%=6e4;const s=Math.floor(d/1e3);$('#days').textContent=String(day).padStart(2,'0');$('#hours').textContent=String(h).padStart(2,'0');$('#minutes').textContent=String(m).padStart(2,'0');$('#seconds').textContent=String(s).padStart(2,'0')}tick();setInterval(tick,1000);
$('#copyAccount').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#accountNumber').textContent.trim());$('#copyStatus').textContent='Nomor rekening berhasil disalin.';}catch(e){$('#copyStatus').textContent='Salin manual: 1400021947107';}setTimeout(()=>$('#copyStatus').textContent='Klik untuk menyalin nomor rekening.',2500)});
$('#rsvpForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#guestName').value.trim();const attendance=$('#attendance').value;const count=$('#guestCount').value;const msg=$('#message').value.trim();const text=`Halo Windra & Winda, saya ${name}.\n\nKehadiran: ${attendance}\nJumlah tamu: ${count}${msg?`\nUcapan: ${msg}`:''}\n\nTerima kasih.`;window.open('https://wa.me/6287820649530?text='+encodeURIComponent(text),'_blank','noopener')});
const imgs=[...document.querySelectorAll('.gallery-grid img')].map(x=>x.src);let idx=0;const lb=$('#lightbox');function show(i){idx=(i+imgs.length)%imgs.length;$('#lbImg').src=imgs[idx];$('#lbCounter').textContent=String(idx+1).padStart(2,'0')+' / '+String(imgs.length).padStart(2,'0');lb.classList.add('open');lb.setAttribute('aria-hidden','false')}document.querySelectorAll('.gallery-grid button').forEach((b,i)=>b.addEventListener('click',()=>show(i)));function closeLb(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true')}$('#lbClose').onclick=closeLb;$('#lbPrev').onclick=()=>show(idx-1);$('#lbNext').onclick=()=>show(idx+1);document.addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='Escape')closeLb();if(e.key==='ArrowLeft')show(idx-1);if(e.key==='ArrowRight')show(idx+1)});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
